# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ixo_world_mobile' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTImage'
  ]
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-camera', path: '../node_modules/react-native-camera'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
end
